language: haskell
dist: xenial

cabal: "3.2"

cache:
  timeout: 600
  directories:
    - "$HOME/.cabal/store"

matrix:
  include:
    # - ghc: 8.10.1	
    - ghc: 8.8.3
    - ghc: 8.6.5
    # - ghc: "8.4.4"
    # - ghc: "8.2.2"
    # - ghc: "8.0.2"
    # - ghc: "7.10.3"
    # - ghc: "7.8.4"
    # - ghc: "7.6.3"

before_install:
 - wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.1.0/travis-wait-enhanced_1.1.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
 - mv travis-wait-enhanced /home/travis/bin/
 - travis-wait-enhanced --version
 - chmod +x travis-script.sh
install:
 - ghc --version
 - cabal --version
 - cabal new-update

script:
 - ./travis-script.sh
# - travis-wait-enhanced --interval=1m --timeout=40m -- cabal new-build --enable-tests --enable-benchmarks
# - cabal new-test --enable-tests
# - cabal new-haddock
# - cabal check
# - cabal v2-sdist   # tests that a source-distribution can be generated

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
# commented out because the v2-install version of this doesn't work??
# - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
#   (cd dist-newstyle/sdist && cabal v2-install --force-reinstalls "$SRC_TGZ")